name: CI

on:
  push:
    branches:
      - optimize
      - optimize\_branch
  workflow_dispatch:
    

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            hulintian/c2cuda-dev:v3.0 \
            bash -c "make all ROSE_INSTALL=/workspace/3rdpart/rose_build"
